#!/usr/bin/env python
# encoding: utf-8

name = "Retroene/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["ene", "enophile"], ownReverse=False)

reverse = "Ene_Reaction"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['BREAK_BOND', '*5', 1, '*6'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*1', 1, '*6'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*4', 1, '*5'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *3 R!H u0 {2,S} {3,[S,D]}
2 *4 R!H u0 {1,S} {4,[S,D]}
3 *2 R!H u0 {1,[S,D]} {5,[D,T,B]}
4 *5 R!H u0 {2,[S,D]} {6,S}
5 *1 R!H u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-2R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    R!H ux {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-2R!H-R_Ext-2R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,S}
2 *4 C   u0 {1,S} {4,S} {7,[S,D,T,B]} {8,[S,D,T,B]}
3 *2 C   u0 {1,S} {5,[D,T,B]}
4 *5 C   u0 {2,S} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    R!H ux {2,[S,D,T,B]}
8    R!H ux {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R",
    group = 
"""
1 *3 O   u0 r0 {2,S} {3,S}
2 *4 C   u0 r0 {1,S} {4,S} {7,[S,D,T,B]} {8,[S,D,T,B]}
3 *2 C   u0 {1,S} {5,[D,T,B]}
4 *5 C   u0 r0 {2,S} {6,S} {9,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 r0 {4,S}
7    R!H ux {2,[S,D,T,B]}
8    R!H ux {2,[S,D,T,B]}
9    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-2R!H-R_Ext-2R!H-R_Ext-3R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,S}
2 *4 C   u0 {1,S} {4,S} {7,[S,D,T,B]} {8,[S,D,T,B]}
3 *2 C   u0 {1,S} {5,D} {9,S}
4 *5 C   u0 {2,S} {6,S}
5 *1 O   u0 {3,D}
6 *6 H   u0 {4,S}
7    R!H ux {2,[S,D,T,B]}
8    R!H ux {2,[S,D,T,B]}
9    C   u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-2R!H-R_Ext-2R!H-R_Ext-3R!H-R_Ext-9R!H-R",
    group = 
"""
1  *3 O   u0 r0 {2,S} {3,S}
2  *4 C   u0 r0 {1,S} {4,S} {7,[S,D,T,B]} {8,[S,D,T,B]}
3  *2 C   u0 r0 {1,S} {5,D} {9,S}
4  *5 C   u0 r0 {2,S} {6,S}
5  *1 O   u0 r0 {3,D}
6  *6 H   u0 r0 {4,S}
7     R!H ux {2,[S,D,T,B]}
8     R!H ux {2,[S,D,T,B]}
9     C   u0 r0 {3,S} {10,[S,D,T,B]}
10    R!H ux {9,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-2R!H-R_7R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    O ux {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-2R!H-R_N-7R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {2,[S,D,T,B]} {8,[S,D,T,B]}
8    C ux {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R",
    group = 
"""
1 *3 O u0 {2,S} {3,S}
2 *4 C u0 {1,S} {4,S} {7,S}
3 *2 C u0 {1,S} {5,D}
4 *5 C u0 {2,S} {6,S} {9,S}
5 *1 O u0 {3,D}
6 *6 H u0 {4,S}
7    C u0 {2,S} {8,[S,D,T,B]}
8    C ux {7,[S,D,T,B]}
9    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R_7C-inRing",
    group = 
"""
1 *3 O u0 r0 {2,S} {3,S}
2 *4 C u0 r0 {1,S} {4,S} {7,S}
3 *2 C u0 r0 {1,S} {5,D}
4 *5 C u0 r0 {2,S} {6,S} {9,S}
5 *1 O u0 r0 {3,D}
6 *6 H u0 r0 {4,S}
7    C u0 r1 {2,S} {8,[S,D,T,B]}
8    C ux {7,[S,D,T,B]}
9    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R_N-7C-inRing",
    group = 
"""
1 *3 O u0 r0 {2,S} {3,S}
2 *4 C u0 r0 {1,S} {4,S} {7,S}
3 *2 C u0 r0 {1,S} {5,D}
4 *5 C u0 r0 {2,S} {6,S} {9,S}
5 *1 O u0 r0 {3,D}
6 *6 H u0 r0 {4,S}
7    C u0 r0 {2,S} {8,[S,D,T,B]}
8    C ux {7,[S,D,T,B]}
9    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux {2,[S,D,T,B]} {8,[S,D,T,B]}
8    C   ux {7,[S,D,T,B]} {9,[S,D,T,B]}
9    R!H ux {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_Ext-8R!H-R",
    group = 
"""
1  *3 O   u0 r0 {2,S} {3,S}
2  *4 C   u0 r0 {1,S} {4,S} {7,S}
3  *2 C   u0 r0 {1,S} {5,D}
4  *5 C   u0 r0 {2,S} {6,S}
5  *1 O   u0 r0 {3,D}
6  *6 H   u0 r0 {4,S}
7     C   u0 {2,S} {8,[S,D,T,B]}
8     C   u0 {7,[S,D,T,B]} {9,[S,D,T,B]} {10,[S,D,T,B]}
9     R!H ux {8,[S,D,T,B]}
10    R!H ux {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_Sp-9R!H=8R!H",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {2,[S,D,T,B]} {8,[S,D,T,B]}
8    C ux {7,[S,D,T,B]} {9,D}
9    C ux {8,D}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H",
    group = 
"""
1 *3 O u0 {2,S} {3,S}
2 *4 C u0 {1,S} {4,S} {7,S}
3 *2 C u0 {1,S} {5,D}
4 *5 C u0 {2,S} {6,S}
5 *1 O u0 {3,D}
6 *6 H u0 {4,S}
7    C u0 {2,S} {8,[S,D,T,B]}
8    C u0 {7,[S,D,T,B]} {9,[S,B]}
9    C u0 {8,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H_7C-inRing",
    group = 
"""
1 *3 O u0 r0 {2,S} {3,S}
2 *4 C u0 r0 {1,S} {4,S} {7,S}
3 *2 C u0 r0 {1,S} {5,D}
4 *5 C u0 r0 {2,S} {6,S}
5 *1 O u0 r0 {3,D}
6 *6 H u0 r0 {4,S}
7    C u0 r1 {2,S} {8,[S,D,T,B]}
8    C u0 {7,[S,D,T,B]} {9,[S,B]}
9    C u0 {8,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H_N-7C-inRing",
    group = 
"""
1 *3 O u0 r0 {2,S} {3,S}
2 *4 C u0 r0 {1,S} {4,S} {7,S}
3 *2 C u0 r0 {1,S} {5,D}
4 *5 C u0 r0 {2,S} {6,S}
5 *1 O u0 r0 {3,D}
6 *6 H u0 r0 {4,S}
7    C u0 r0 {2,S} {8,[S,D,T,B]}
8    C u0 {7,[S,D,T,B]} {9,[S,B]}
9    C u0 {8,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {2,[S,D,T,B]}
8    C ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {2,[S,D,T,B]}
8    C ux {4,[S,D,T,B]} {9,[S,D,T,B]}
9    C u0 {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R_Sp-9R!H-8R!H",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux r0 {2,[S,D,T,B]}
8    C ux {4,[S,D,T,B]} {9,S}
9    C u0 r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R_N-Sp-9R!H-8R!H",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux r0 {2,[S,D,T,B]}
8    C ux {4,[S,D,T,B]} {9,[B,D,T]}
9    C u0 r0 {8,[B,D,T]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_Ext-2R!H-R_N-7R!H->O_Ext-3R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]} {7,[S,D,T,B]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]} {8,[S,D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux r0 {2,[S,D,T,B]}
8    R!H ux {3,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_Ext-5R!H-R",
    group = 
"""
1 *3 R!H u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 C   u0 {3,[D,T,B]} {7,[S,D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux {5,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_Ext-5R!H-R_1R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,B}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 C u0 {3,B} {7,B}
6 *6 H u0 {4,S}
7    C ux {5,B}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_Ext-5R!H-R_1R!H->O_Ext-4R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 r1 {1,[S,D]} {5,B}
4 *5 C   u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 C   u0 r1 {3,B} {7,B}
6 *6 H   u0 {4,S}
7    C   ux r1 {5,B}
8    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_Ext-5R!H-R_N-1R!H->O",
    group = 
"""
1 *3 C u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,D}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 C u0 {3,D} {7,S}
6 *6 H u0 {4,S}
7    C ux {5,S}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_Ext-5R!H-R_N-1R!H->O_Ext-4R!H-R",
    group = 
"""
1 *3 C   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 r0 {1,[S,D]} {5,D}
4 *5 C   u0 {2,[S,D]} {6,S} {8,[S,D,T,B]}
5 *1 C   u0 r0 {3,D} {7,S}
6 *6 H   u0 {4,S}
7    C   ux r0 {5,S}
8    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_Ext-1R!H-R",
    group = 
"""
1 *3 R!H u0 {2,S} {3,[S,D]} {7,[S,D,T,B]}
2 *4 R!H u0 {1,S} {4,[S,D]}
3 *2 C   u0 r0 {1,[S,D]} {5,D}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 R!H u0 r0 {3,D}
6 *6 H   u0 {4,S}
7    R!H ux {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_Ext-4R!H-R",
    group = 
"""
1 *3 R!H u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 R!H u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_Ext-4R!H-R_1R!H->O",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_Ext-4R!H-R_1R!H->O_7R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,D}
4 *5 C u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O u0 {3,D}
6 *6 H u0 {4,S}
7    O ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_Ext-4R!H-R_1R!H->O_7R!H->O_Ext-7O-R_Ext-8R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 r0 {1,[S,D]} {5,D}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O   u0 r0 {3,D}
6 *6 H   u0 {4,S}
7    O   ux {4,[S,D,T,B]} {8,S}
8    C   u0 r0 {7,S} {9,[S,D,T,B]}
9    R!H ux {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_7C-inRing",
    group = 
"""
1 *3 O u0 r0 {2,S} {3,S}
2 *4 C u0 r0 {1,S} {4,S}
3 *2 C u0 {1,S} {5,[D,T,B]}
4 *5 C u0 r0 {2,S} {6,S} {7,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 r0 {4,S}
7    C u0 r1 {4,S}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C ux r0 {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux r0 {4,[S,D,T,B]} {8,[S,D,T,B]}
8    R!H ux {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-4R!H-R",
    group = 
"""
1 *3 O   u0 r0 {2,S} {3,S}
2 *4 C   u0 r0 {1,S} {4,S}
3 *2 C   u0 {1,S} {5,[D,T,B]}
4 *5 C   u0 r0 {2,S} {6,S} {7,S} {9,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 r0 {4,S}
7    C   u0 r0 {4,S} {8,S}
8    C   u0 r0 {7,S}
9    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-7C-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux r0 {4,[S,D,T,B]} {8,[S,D,T,B]} {9,[S,D,T,B]}
8    R!H ux {7,[S,D,T,B]}
9    R!H ux {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-8R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux r0 {4,[S,D,T,B]} {8,[S,D,T,B]}
8    C   ux {7,[S,D,T,B]} {9,[S,D,T,B]}
9    R!H ux {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-4R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]} {8,[S,D,T,B]}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    C   ux r0 {4,[S,D,T,B]}
8    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_Ext-4R!H-R_N-1R!H->O",
    group = 
"""
1 *3 C u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,D}
4 *5 C u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 C u0 {3,D}
6 *6 H u0 {4,S}
7    C ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R",
    group = 
"""
1 *3 C   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,D}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 C   u0 {3,D}
6 *6 H   u0 {4,S}
7    C   ux {4,[S,D,T,B]} {8,[S,D,T,B]}
8    R!H ux {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R_Ext-8R!H-R",
    group = 
"""
1 *3 C   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,D}
4 *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5 *1 C   u0 {3,D}
6 *6 H   u0 {4,S}
7    C   ux {4,[S,D,T,B]} {8,S}
8    R!H ux {7,S} {9,S}
9    R!H u0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R_Ext-8R!H-R_Ext-7R!H-R",
    group = 
"""
1  *3 C   u0 {2,S} {3,[S,D]}
2  *4 C   u0 {1,S} {4,[S,D]}
3  *2 C   u0 r0 {1,[S,D]} {5,D}
4  *5 C   u0 {2,[S,D]} {6,S} {7,[S,D,T,B]}
5  *1 C   u0 r0 {3,D}
6  *6 H   u0 {4,S}
7     C   ux r0 {4,[S,D,T,B]} {8,S} {10,[S,D,T,B]}
8     R!H ux {7,S} {9,S}
9     R!H u0 r0 {8,S}
10    R!H ux {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_2R!H->C",
    group = 
"""
1 *3 R!H u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 R!H u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_2R!H->C_1R!H->O",
    group = 
"""
1 *3 O   u0 {2,S} {3,[S,D]}
2 *4 C   u0 {1,S} {4,[S,D]}
3 *2 C   u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C   u0 {2,[S,D]} {6,S}
5 *1 R!H u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_2R!H->C_1R!H->O_Ext-3R!H-R",
    group = 
"""
1 *3 O   u0 {2,S} {3,S}
2 *4 C   u0 {1,S} {4,S}
3 *2 C   u0 {1,S} {5,[D,T,B]} {7,S}
4 *5 C   u0 {2,S} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 {4,S}
7    R!H u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C",
    group = 
"""
1 *3 O u0 {2,S} {3,S}
2 *4 C u0 {1,S} {4,S}
3 *2 C u0 {1,S} {5,[D,T,B]} {7,S}
4 *5 C u0 {2,S} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C_Ext-7C-R",
    group = 
"""
1 *3 O u0 {2,S} {3,S}
2 *4 C u0 {1,S} {4,S}
3 *2 C u0 {1,S} {5,[D,T,B]} {7,S}
4 *5 C u0 {2,S} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
7    C u0 {3,S} {8,S}
8    C u0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C_Ext-7C-R_Ext-8R!H-R",
    group = 
"""
1 *3 O   u0 r0 {2,S} {3,S}
2 *4 C   u0 r0 {1,S} {4,S}
3 *2 C   u0 {1,S} {5,[D,T,B]} {7,S}
4 *5 C   u0 r0 {2,S} {6,S}
5 *1 O   u0 {3,[D,T,B]}
6 *6 H   u0 r0 {4,S}
7    C   u0 r0 {3,S} {8,S}
8    C   u0 r0 {7,S} {9,[S,D,T,B]}
9    R!H ux {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_2R!H->C_1R!H->O_Ext-3R!H-R_N-7R!H->C",
    group = 
"""
1 *3 O             u0 r0 {2,S} {3,S}
2 *4 C             u0 r0 {1,S} {4,S}
3 *2 C             u0 {1,S} {5,[D,T,B]} {7,S}
4 *5 C             u0 r0 {2,S} {6,S}
5 *1 O             u0 {3,[D,T,B]}
6 *6 H             u0 r0 {4,S}
7    [S,N,Si,Cl,O] u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_2R!H->C_1R!H->O_5R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 O u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_2R!H->C_1R!H->O_N-5R!H->O",
    group = 
"""
1 *3 O u0 {2,S} {3,[S,D]}
2 *4 C u0 {1,S} {4,[S,D]}
3 *2 C u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 C u0 {3,[D,T,B]}
6 *6 H u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_2R!H->C_N-1R!H->O",
    group = 
"""
1 *3 C   u0 r0 {2,S} {3,S}
2 *4 C   u0 r0 {1,S} {4,S}
3 *2 C   u0 {1,S} {5,[D,T,B]}
4 *5 C   u0 r0 {2,S} {6,S}
5 *1 R!H u0 {3,[D,T,B]}
6 *6 H   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_N-2R!H->C",
    group = 
"""
1 *3 C       u0 {2,S} {3,[S,D]}
2 *4 [O,S,N] u0 {1,S} {4,[S,D]}
3 *2 C       u0 {1,[S,D]} {5,[D,T,B]}
4 *5 C       u0 {2,[S,D]} {6,S}
5 *1 C       u0 {3,[D,T,B]}
6 *6 H       u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_N-2R!H->C_2NOS->S",
    group = 
"""
1 *3 C u0 r0 {2,S} {3,S}
2 *4 S u0 r0 {1,S} {4,S}
3 *2 C u0 {1,S} {5,[D,T,B]}
4 *5 C u0 r0 {2,S} {6,S}
5 *1 C u0 {3,[D,T,B]}
6 *6 H u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_N-2R!H->C_N-2NOS->S",
    group = 
"""
1 *3 C     u0 {2,S} {3,[S,D]}
2 *4 [O,N] u0 {1,S} {4,[S,D]}
3 *2 C     u0 {1,[S,D]} {5,D}
4 *5 C     u0 {2,[S,D]} {6,S}
5 *1 C     u0 {3,D}
6 *6 H     u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_N-2R!H->C_N-2NOS->S_2NO->O",
    group = 
"""
1 *3 C u0 {2,S} {3,[S,D]}
2 *4 O u0 {1,S} {4,[S,D]}
3 *2 C u0 r0 {1,[S,D]} {5,D}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 C u0 r0 {3,D}
6 *6 H u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_N-2R!H->C_N-2NOS->S_N-2NO->O",
    group = 
"""
1 *3 C u0 {2,S} {3,[S,D]}
2 *4 N u0 {1,S} {4,[S,D]}
3 *2 C u0 r0 {1,[S,D]} {5,D}
4 *5 C u0 {2,[S,D]} {6,S}
5 *1 C u0 r0 {3,D}
6 *6 H u0 {4,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-2R!H-R
        L3: Root_Ext-2R!H-R_Ext-2R!H-R
            L4: Root_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R
            L4: Root_Ext-2R!H-R_Ext-2R!H-R_Ext-3R!H-R
                L5: Root_Ext-2R!H-R_Ext-2R!H-R_Ext-3R!H-R_Ext-9R!H-R
        L3: Root_Ext-2R!H-R_7R!H->O
        L3: Root_Ext-2R!H-R_N-7R!H->O
            L4: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R
                L5: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R_7C-inRing
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-4R!H-R_N-7C-inRing
                L5: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_Ext-8R!H-R
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_Sp-9R!H=8R!H
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H
                        L7: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H_7C-inRing
                        L7: Root_Ext-2R!H-R_N-7R!H->O_Ext-7C-R_Ext-8R!H-R_N-Sp-9R!H=8R!H_N-7C-inRing
            L4: Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R
                L5: Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R_Sp-9R!H-8R!H
                    L6: Root_Ext-2R!H-R_N-7R!H->O_Ext-4R!H-R_Ext-8R!H-R_N-Sp-9R!H-8R!H
            L4: Root_Ext-2R!H-R_N-7R!H->O_Ext-3R!H-R
    L2: Root_Ext-5R!H-R
        L3: Root_Ext-5R!H-R_1R!H->O
            L4: Root_Ext-5R!H-R_1R!H->O_Ext-4R!H-R
        L3: Root_Ext-5R!H-R_N-1R!H->O
            L4: Root_Ext-5R!H-R_N-1R!H->O_Ext-4R!H-R
    L2: Root_Ext-1R!H-R
    L2: Root_Ext-4R!H-R
        L3: Root_Ext-4R!H-R_1R!H->O
            L4: Root_Ext-4R!H-R_1R!H->O_7R!H->O
                L5: Root_Ext-4R!H-R_1R!H->O_7R!H->O_Ext-7O-R_Ext-8R!H-R
            L4: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O
                L5: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_7C-inRing
                L5: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing
                    L6: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R
                        L7: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-4R!H-R
                        L7: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-7C-R
                        L7: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-7C-R_Ext-8R!H-R
                    L6: Root_Ext-4R!H-R_1R!H->O_N-7R!H->O_N-7C-inRing_Ext-4R!H-R
        L3: Root_Ext-4R!H-R_N-1R!H->O
            L4: Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R
                L5: Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R_Ext-8R!H-R
                    L6: Root_Ext-4R!H-R_N-1R!H->O_Ext-7R!H-R_Ext-8R!H-R_Ext-7R!H-R
    L2: Root_2R!H->C
        L3: Root_2R!H->C_1R!H->O
            L4: Root_2R!H->C_1R!H->O_Ext-3R!H-R
                L5: Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C
                    L6: Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C_Ext-7C-R
                        L7: Root_2R!H->C_1R!H->O_Ext-3R!H-R_7R!H->C_Ext-7C-R_Ext-8R!H-R
                L5: Root_2R!H->C_1R!H->O_Ext-3R!H-R_N-7R!H->C
            L4: Root_2R!H->C_1R!H->O_5R!H->O
            L4: Root_2R!H->C_1R!H->O_N-5R!H->O
        L3: Root_2R!H->C_N-1R!H->O
    L2: Root_N-2R!H->C
        L3: Root_N-2R!H->C_2NOS->S
        L3: Root_N-2R!H->C_N-2NOS->S
            L4: Root_N-2R!H->C_N-2NOS->S_2NO->O
            L4: Root_N-2R!H->C_N-2NOS->S_N-2NO->O
"""
)

