#!/usr/bin/env python
# encoding: utf-8

name = "Surface/Ammonia_Pt211_oxidation-seed"
shortDesc = ""
longDesc = """
This library is built to import training reactions, based on:
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251

Training reactions removed using kinetics_library_to_training notebook
"""
autoGenerated=False
entry(
    index = 0,
    label = "O2 + X + X <=> O_X + O_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.018, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """O2 Surface_Adsorption_Dissociative""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
The pressure of adsorption processes: P= 1 bar = 10E5 Pa
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 1,
    label = "NH3_X + OH_X <=> NH2_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.113e+21,'cm^2/(mol*s)'), n=0, Ea=(80087,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Surface_Abstraction_Single_vdW""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 8.2E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 2,
    label = "NH2_X + OH_X <=> NH_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.481e+21,'cm^2/(mol*s)'), n=0, Ea=(76227,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Surface_Abstraction_vdW""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 3.9E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 3,
    label = "NH_X + OH_X <=> N_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.012e+21,'cm^2/(mol*s)'), n=0, Ea=(81052,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Surface_Abstraction_vdW""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 5.3E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 4,
    label = "OH_X + OH_X <=> O_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.595e+21,'cm^2/(mol*s)'), n=0, Ea=(81052,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Reverse R95""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 4.2E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 5,
    label = "N2 + X + X <=> N_X + N_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=4.7e-07, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """N2 Surface_Adsorption_Dissociative""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
The pressure of adsorption processes: P= 1 bar = 10E5 Pa
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 6,
    label = "N_X + O_X <=> NO_X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.443e+21,'cm^2/(mol*s)'), n=0, Ea=(140875,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Nitrogen/51""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 3.8E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

entry(
    index = 7,
    label = "N_X + NO_X <=> N2O_X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.316e+21,'cm^2/(mol*s)'), n=0, Ea=(156314,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    shortDesc = """Reverse R34""",
    longDesc = 
"""
"Structure- and Temperature-Dependence of Pt-Catalyzed Ammonia Oxidation Rates and Selectivities."
DMa, Hanyu; Schneider, William F.(2019). ACS Catalysis, 9(3), 2407-2414. 
https://doi.org/10.1021/acscatal.8b04251
This reaction used RMG's surface site density of Pt211 = 2.634E-9(mol/cm^2) to calculate the A factor.
A = 6.1E12(1/s)/2.634E-9(mol/cm^2)
""",
    metal = "Pt",
    facet = "211",
)

